=== TeamBuilderApp/Centivo/MongoDB_Util/schema-Centivo-users-mongoDBJSON.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": [
    "_id",
    "age",
    "email",
    "id",
    "name"
  ],
  "properties": {
    "_id": {
      "$ref": "#/$defs/ObjectId"
    },
    "age": {
      "type": "integer"
    },
    "email": {
      "type": "string"
    },
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    }
  },
  "$defs": {
    "ObjectId": {
      "type": "object",
      "properties": {
        "$oid": {
          "type": "string",
          "pattern": "^[0-9a-fA-F]{24}$"
        }
      },
      "required": [
        "$oid"
      ],
      "additionalProperties": false
    }
  }
}

=== TeamBuilderApp/Centivo/MongoDB_Util/Centivo.users.json
[{
  "_id": {
    "$oid": "67f23c467907f5997125175d"
  },
  "id": 0,
  "name": "John Doe",
  "email": "johndoe@email.com",
  "age": 30
},
{
  "_id": {
    "$oid": "68f23c467907f5997125175d"
  },
  "id": 1,
  "name": "Jane Doe",
  "email": "janedoe@email.com",
  "age": 22
},
{
  "_id": {
    "$oid": "69f23c467907f5997125175d"
  },
  "id": 2,
  "name": "Fred Doe",
  "email": "freddoe@email.com",
  "age": 28
},
{
  "_id": {
    "$oid": "70f23c467907f5997125175d"
  },
  "id": 3,
  "name": "Fran Doe",
  "email": "frandoe@email.com",
  "age": 29
},
{
  "_id": {
    "$oid": "71f23c467907f5997125175d"
  },
  "id": 4,
  "name": "Jed Doe",
  "email": "jeddoe@email.com",
  "age": 34
}]
